package cinder.geom;

public enum Attrib {
    POSITION, COLOR, TEX_COORD_0, TEX_COORD_1, TEX_COORD_2, TEX_COORD_3,
    NORMAL, TANGENT, BITANGENT, BONE_INDEX, BONE_WEIGHT,
    CUSTOM_0, CUSTOM_1, CUSTOM_2, CUSTOM_3, CUSTOM_4, CUSTOM_5, CUSTOM_6, CUSTOM_7, CUSTOM_8, CUSTOM_9,
    NUM_ATTRIBS, USER_DEFINED
}
